
services:
  frontend:
    container_name:  frontend
    build:
      context: ./vue3
    ports:
      - "5173:5173"

    volumes:
      - ./vue3/projectvue:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./dotnet
    ports:
      - "5096:80"
      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
# This network is used to connect the services together
  default:
# Set the network name
    name: vue-network

    driver: bridge