name: gh-action-vue
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Trigger Render Deploy
              run: |
                curl -X POST https://api.render.com/v1/services/srv-d1hq77vfte5s73alkmag/deploys \
                -H "Accept: application/json" \
                -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

